<?php
return array (
  'database' =>
  array (
    'driver' => 'Db_Driver_PDO_Mysql',
    'host' => 'localhost',
    'base' => 'cogear',
    'user' => 'root',
    'pass' => '',
    'port' => '3306',
    'prefix' => '',
  ),
  'gears' =>
  array(
        0 => 'Access',
        1 => 'Admin',
        2 => 'Ajax',
        3 => 'Assets',
        4 => 'Bootstrap',
        5 => 'Breadcrumb',
        6 => 'Cache',
        7 => 'DateTime',
        8 => 'Db',
        9 => 'Dev',
        10 => 'Errors',
        11 => 'Fancybox',
        12 => 'File',
        13 => 'Form',
        14 => 'Gears',
        15 => 'Geo',
        16 => 'Lang',
        17 => 'Icons',
        18 => 'Image',
        19 => 'Input',
        20 => 'Log',
        21 => 'Mail',
        22 => 'Menu',
        23 => 'Meta',
        24 => 'Modal',
        25 => 'Notify',
        26 => 'Pager',
        27 => 'Parser',
        28 => 'Request',
        29 => 'Response',
        30 => 'Roles',
        31 => 'Router',
        32 => 'Secure',
        33 => 'Session',
        34 => 'Table',
        35 => 'Template',
        36 => 'Theme',
        37 => 'User',
        38 => 'Zip',
        39 => 'jQuery',
    ),
  'permitted_uri_chars' => 'а-яa-z0-9\\s_\\.\\-',
  'key' => 'ba96917974845ff8a6f178c9551c17c7',
);