<?php 
return array (
  'database' => 
  array (
    'driver' => 'Db_Driver_PDO_Mysql',
    'host' => 'localhost',
    'base' => 'cogear',
    'user' => 'root',
    'pass' => NULL,
    'port' => NULL,
    'prefix' => NULL,
  ),
  'gears' => 
  array (
    0 => 'Access',
    1 => 'Admin',
    2 => 'Ajax',
    3 => 'Assets',
    4 => 'Bootstrap',
    5 => 'Breadcrumb',
    6 => 'Cache',
    7 => 'DateTime',
    8 => 'Db',
    9 => 'Dev',
    10 => 'Errors',
    11 => 'File',
    12 => 'Form',
    13 => 'Gears',
    14 => 'I18n',
    15 => 'Icons',
    16 => 'Image',
    17 => 'Input',
    18 => 'Jevix',
    19 => 'Mail',
    20 => 'Menu',
    21 => 'Meta',
    22 => 'Modal',
    23 => 'Notify',
    24 => 'Pager',
    25 => 'Post',
    26 => 'Request',
    27 => 'Response',
    28 => 'Router',
    29 => 'Roles',
    30 => 'Secure',
    31 => 'Session',
    32 => 'Table',
    33 => 'Template',
    34 => 'Theme',
    35 => 'User',
    36 => 'Zip',
    37 => 'jQuery',
  ),
  'permitted_uri_chars' => 'а-яa-z0-9\s_\.\-',
  'key' => 'ba96917974845ff8a6f178c9551c17c7',
  'site' => 
  array (
    'name' => 'cogear',
    'development' => 1,
    'url' => 'cogear.new',
  ),
  'mail' => 
  array (
    'from' => 'admin@cogear.ru',
    'from_name' => 'cogear',
    'signature' => '<p>-----------------------<br/>С уважением,<br/>почтально сайта http://cogear.ru',
  ),
);