<?php

return array(
    'database' =>
    array(
        'driver' => 'Db_Driver_PDO_Mysql',
        'host' => 'localhost',
        'base' => 'cogear',
        'user' => 'root',
        'pass' => NULL,
        'port' => NULL,
        'prefix' => NULL,
    ),
    'gears' =>
    array(
        0 => 'Access',
        1 => 'Admin',
        2 => 'Ajax',
        3 => 'Assets',
        4 => 'Bootstrap',
        5 => 'Breadcrumb',
        6 => 'Cache',
        7 => 'DateTime',
        8 => 'Db',
        9 => 'Dev',
        10 => 'Errors',
        11 => 'Fancybox',
        12 => 'File',
        13 => 'Form',
        14 => 'Gears',
        15 => 'I18n',
        16 => 'Icons',
        17 => 'Image',
        18 => 'Input',
        19 => 'Jevix',
        20 => 'Mail',
        21 => 'Menu',
        22 => 'Meta',
        23 => 'Modal',
        24 => 'Notify',
        25 => 'Pager',
        26 => 'Post',
        27 => 'Request',
        28 => 'Response',
        29 => 'Router',
        30 => 'Roles',
        31 => 'Secure',
        32 => 'Session',
        33 => 'Table',
        34 => 'Template',
        35 => 'Theme',
        36 => 'User',
        37 => 'Zip',
        38 => 'jQuery',
    ),
    'permitted_uri_chars' => 'а-яa-z0-9\s_\.\-',
    'key' => 'ba96917974845ff8a6f178c9551c17c7',
    'site' =>
    array(
        'url' => 'cogear.new',
    ),
    'mail' =>
    array(
        'from' => 'admin@cogear.ru',
        'from_name' => 'cogear',
        'signature' => '<p>-----------------------<br/>С уважением,<br/>почтально сайта http://cogear.ru',
    ),
);